### ISSUE TITLE
MySQL error : cannot connect to database '': What database is it using and where is it configured ?

### ISSUE THREAD

**Issue by eLvErDe** [centreon/centreon-gorgone#168]
Hello,

After upgrading 19.10 to 20.04 running on Debian 10, I'm trying to get gorgone working but it's failing with logs that does not make any sense to me:

```
Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/gorgone/class/db.pm line 241.
Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/gorgone/class/db.pm line 254.
2021-11-23 15:30:23 - ERROR - MySQL error : cannot connect to database '': Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) (caller: gorgone::class::db:/usr/share/perl5/gorgone/class/db.pm:316) (try: 1)
2021-11-23 15:30:23 - ERROR - [legacycmd] Cannot get configuration for pollers
```

The thing is, that's there's no local MySQL server, so no `/var/run/mysqld/mysqld.sock` anywhere but I never used such setup so I don't know why it's accessing this. Other relevant files I can see are

**/etc/centreon/config.d/10-database.yaml**

```yaml
database:
  db_configuration:
    dsn: "mysql:host=172.17.0.1:3306;dbname=centreon"
    username: "centreon"
    password: "password"
  db_realtime:
    dsn: "mysql:host=172.17.0.1:3306;dbname=centreon_storage"
    username: "centreon"
    password: "password"
```
And **/etc/centreon-gorgone/config.d/40-gorgoned.yaml**

```yaml
name: gorgoned-Central
description: Configuration for remote server Central
gorgone:
  gorgonecore:
    privkey: "/var/lib/centreon-gorgone/.keys/rsakey.priv.pem"
    pubkey: "/var/lib/centreon-gorgone/.keys/rsakey.pub.pem"
  modules:
    - name: httpserver
      package: "gorgone::modules::core::httpserver::hooks"
      enable: true
      address: "0.0.0.0"
      port: "8085"
      ssl: false
      auth:
        enabled: false
      allowed_hosts:
        enabled: true
        subnets:
          - 127.0.0.1/32
    - name: action
      package: "gorgone::modules::core::action::hooks"
      enable: true
    - name: cron
      package: "gorgone::modules::core::cron::hooks"
      enable: true
      cron: !include cron.d/*.yaml
    - name: nodes
      package: "gorgone::modules::centreon::nodes::hooks"
      enable: true
    - name: proxy
      package: "gorgone::modules::core::proxy::hooks"
      enable: true
    - name: legacycmd
      package: "gorgone::modules::centreon::legacycmd::hooks"
      enable: true
      cmd_dir: "/var/lib/centreon/centcore/"
      cmd_file: "/var/lib/centreon/centcore.cmd"
      cache_dir: "/var/cache/centreon"
      cache_dir_trap: "/etc/snmp/centreon_traps"
      remote_dir: "/var/cache/centreon/config/remote-data/"
    - name: engine
      package: "gorgone::modules::centreon::engine::hooks"
      enable: true
      command_file: "/var/lib/centreon-engine/rw/centengine.cmd"
    - name: statistics
      package: "gorgone::modules::centreon::statistics::hooks"
      enable: true
      broker_cache_dir: "/var/cache/centreon/broker-stats/"
      cron:
        - id: broker_stats
          timespec: "*/5 * * * *"
          action: BROKERSTATS
          parameters:
            timeout: 10
        - id: engine_stats
          timespec: "*/5 * * * *"
          action: ENGINESTATS
          parameters:
            timeout: 10
```

And gorgoned seems to create an SQLite database on start at **/var/lib/centreon-gorgone/history.sdb**

So what's going on here ?

Regards, Adam.

**Comment by garnier-quentin** [comment]
Could you provide a full debug mode ? and a archive of the directory /etc/centreon-gorgone/ ?

**Comment by eLvErDe** [comment]
I think so, if you tell me how to go full debug mode ;-)

**Comment by eLvErDe** [comment]
For /etc/centreon-gorgone, only two files, the one I pasted above and **/etc/centreon-gorgone/config.yaml** containing

```yaml
name: config.yaml
description: Configuration brought by Centreon Gorgone package. SHOULD NOT BE EDITED! USE CONFIG.D DIRECTORY!
configuration: !include /etc/centreon-gorgone/config.d/*.yaml
```
