### ISSUE TITLE
Wrong format for the mysql connection

### ISSUE THREAD

**Issue by pkriko** [centreon/centreon-gorgone#37]
Hello,

If we used a custom port for MySQL, gorgoned can't connect to the database :
```
2020-07-28 11:02:05 - ERROR - MySQL error : cannot connect to database 2020-07-28 14:56:20 - ERROR - MySQL error : cannot connect to database 'mysql:host=10.10.1.36:3316;dbname=centreon': Can't connect to MySQL server on '10.10.1.36' (111 "Connection refused") (caller: gorgone::class::db:/usr/share/perl5/vendor_perl/gorgone/class/db.pm:278) (try: 0)
2020-07-28 14:56:21 - ERROR - MySQL error : cannot connect to database 'mysql:host=10.10.1.36:3316;dbname=centreon': Can't connect to MySQL server on '10.10.1.36' (111 "Connection refused") (caller: gorgone::class::db:/usr/share/perl5/vendor_perl/gorgone/class/db.pm:278) (try: 1)

```

Cause of the wrong syntax in the configuration file `/etc/centreon/config.d/10-database.yaml` :
```
database:
  db_configuration:
    dsn: "mysql:host=10.10.1.36:3316;dbname=centreon"
    username: "centreon"
    password: "centreon"
  db_realtime:
    dsn: "mysql:host=10.10.1.36:3316;dbname=centreon_storage"
    username: "centreon"
    password: "centreon"
```

should be :
```
database:
  db_configuration:
    dsn: "mysql:host=10.10.1.36;port=3316;dbname=centreon"
    username: "centreon"
    password: "centreon"
  db_realtime:
    dsn: "mysql:host=10.10.1.36;port=3316;dbname=centreon_storage"
    username: "centreon"
    password: "centreon"
```
